# Generated by Django 4.0.4 on 2022-04-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
